name: Publish Package

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  publish:
    name: build_package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package
        id: create_package
        shell: bash
        run: |
          tag=$(git describe --tags --always)
          release_name="cmdb.bundle-${tag}"

          # Pack files
          mkdir -p ./cmdb.bundle
          cp -rv ./Contents ./cmdb.bundle
          cp -v ./README.md ./cmdb.bundle
          7z a -tzip "${release_name}.zip" ./cmdb.bundle

          # Set outputs using environment file
          {
            echo "release_name=${release_name}"
            echo "release_tag=${tag}"
            echo "filename=${release_name}.zip"
          } >> "${GITHUB_OUTPUT}"

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "${{ steps.create_package.outputs.release_tag }}"
          automatic_release_tag: "${{ steps.create_package.outputs.release_tag }}"
          prerelease: false
          files: |
            *.zip
